User and Orgs Models
helpwave/rest-api pull request #102
Opened 2022-11-13 16:59 UTC by FoseFx

Closes #95

2022-11-13 18:02 UTC, MaxSchaefer requested changes

2022-11-13 18:02 UTC, MaxSchaefer commented on db/migrations/000002_auth.up.sql
> +FOREIGN KEY (owned_by) REFERENCES organizations(id);
Shouldn't `owned_by` actually be an attribute on the `EmergencyRoom` model as well?

2022-11-14 13:23 UTC, FoseFx commented
This is the ERD now btw: https://github.com/helpwave/helpwave/pull/9

2022-11-14 20:19 UTC, MaxSchaefer commented on models/room.go
> +	Organization   Organization
Shouldn't there be a GORM annotation here? Take a look at https://github.com/helpwave/rest-api/blob/main/models/emergency.go#L14.

2022-11-14 21:11 UTC, MaxSchaefer commented on models/room.go
> +	Organization   Organization
Nice, thanks for the clarification 👍

2022-11-14 21:12 UTC, MaxSchaefer approved these changes
Let's get this auth thing started 🎉

2022-11-14 21:13 UTC, merged