issue/21 CreateER
helpwave/rest-api pull request #27
Opened 2022-10-09 14:21 UTC by FoseFx

Closes #21

2022-10-09 18:56 UTC, FoseFx commented on routes/rooms.go
> +	log.Println("req body: ", body)
not sure if this can cause a format string vuln or if this is a fp

2022-10-09 19:00 UTC, FoseFx commented on routes/rooms.go
> +	log.Println("req body: ", body)
ah should have read the advisory, it's about log injections

2022-10-13 13:54 UTC, use-to requested changes

2022-10-16 20:21 UTC, use-to approved these changes
Formatting is perfect now! Thanks

2022-10-16 20:22 UTC, merged